name: CI / CD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Linting:
    runs-on: ubuntu-latest
		steps:
	    - uses: actions/checkout@v4
	    - uses: actions/setup-node@v4
		  - name: Type check files
		    run: npm run type:check
		  - name: Lint files
		    run: npm run lint
  Testing:
	  needs: Linting
	  runs-on: ubuntu-latest
	  steps:
	    - uses: actions/checkout@v4
		  - uses: actions/setup-node@v4
		  - name: Run coverage tests
		    run: npm run test:coverage
  Deployment:
	  needs: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
